### PR TITLE
fix(sensors): fix the sensor data structs when `max-sample-min-count`>1

### LINKED ISSUE #1379: [ariel-os-sensors] cannot compile with max-sample-min-count > 1
### Summary

```
cargo clippy --config ariel-os-cargo.toml -p ariel-os-sensors
```
Does not return any error, but running 

```
cargo clippy --config ariel-os-cargo.toml -p ariel-os-sensors --features "max-sample-min-count-2"
```

Throws an error, looks like there's an issue in the macro, with how the iterators are created in `Samples::samples()` and `ReadingChannels::iter()`.

### Relevant log output

```shell
error[E0308]: `match` arms have incompatible types
  --> src/ariel-os-sensors/src/sensor.rs:17:1
   |
17 | ariel_os_macros::define_count_adjusted_sensor_enums!();
   | ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
   | |
   | expected `1`, found `2`
   | this is found to be of type `core::array::IntoIter<sample::Sample, 1>`
   | `match` arms have incompatible types
   |
   = note: expected struct `core::array::IntoIter<_, 1>`
              found struct `core::array::IntoIter<_, 2>`
```

### Hardware/ Setup

_No response_

### Possible Solution

_No response_

### Would you like to work on fixing this bug?

Yes

### PR DESCRIPTION
**Pull request by ROMemories**
# Description

This fixes #1379, which found a type issue introduced in #1360 that appears when `max-sample-min-count`>1.

## How to review this PR

This PR is better reviewed commit by commit.

## Issues/PRs references

Fixes #1379.

## Change checklist

- [x] I have cleaned up my commit history and squashed fixup commits.
- [x] I have followed the [Coding Conventions](https://ariel-os.github.io/ariel-os/dev/docs/book/coding-conventions.html).
- [x] I have performed a self-review of my own code.
- [x] I have made corresponding changes to the documentation.

### CODE REVIEW

**Comment by ROMemories** [comment]
@nponsard Can you double-check this works in your use case?

**Comment by nponsard** [comment]
This compiles with my use case :+1: 

I tried to fix this myself with the `.iter().copied()` but forgot to put a `ref` like you did.
